codename: Update Documentation
on:
  pull_request:
    branches:
      - main
jobs:
  update-doc:
    name: Update Theneo Documentation
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Update Documentation on Theneo
        uses: Theneo-Inc/api-documentation@1.7.0
        with:
          FILE_PATH:
            - /authentication.yaml
            - /user-management.yaml
          PROJECT_KEY: test-api
          SECRET: 50657846-aa55-447b-a90a-ffd870975af3
          IMPORT_OPTION: merge
          AUTO_PUBLISH: false
          INCLUDE_GITHUB_METADATA: true
